### ISSUE TITLE
2단보기 메모 2단에 나오게

### ISSUE THREAD

**Issue by lifoveBible** [lifoveBible/lifovebible#54]

**Comment by YeeF** [comment]
메모 2단에 나오게?

1단, 2단 구분 없이 
역본 대조 2단 보기에서도 메모가 한쪽으로 칭ㅍ쳐 나타나지 않았음 해요

**Comment by lifoveBible** [comment]
Affected in 7.4.2 Beta
베타버전 테스터가 되어, 수정된 기능이 잘 되는지 확인해 주세요.
https://play.google.com/apps/testing/net.lifove.android.lifovebible

**Comment by YeeF** [comment]
베타 버젼 받고 테스트 했는데,

여전히 메모는 2단 기본 중 1단 화면에만 치우져 나왔어요.
메모는 1,2단 구분 없이 
가로보기 전체줄로 나왔으면 좋겠어요.

애써 주셔서 감사합니다.

**Comment by lifoveBible** [comment]
7.4.2 부터 여러 역본 2단보기시 메모가 2단에 걸쳐서 나오게 했습니다. 업데이트 제대로 하신 것 맞나요? 업데이트 제대로 하셨는데 아니라면, 제가 뭘 원하시는지 이해를 잘 못한 것 같습니다. 자세히 설명 해주시면, 다시 생각해 보겠습니다.

**Comment by lifoveBible** [comment]
아 문제 확인했습니다. 베타버전을 여러번 바꾸면서 새로운 버그가 생겼네요. 다음 업데이트에서 수정하겠습니다.

**Comment by lifoveBible** [comment]
7.4.3 Beta 버전에서 문제를 수정하였습니다. 테스트 해보시고 문제있는지 없는지 알려주세요. 문제 없으면 다음 정식버전에 그대로 배포하겠습니다.

**Comment by YeeF** [comment]
오.. 환상적으로 바뀌었어요. 

정말 환상적입니다. ㅎㅎㅎ

메모 색상(초록)이 본문 색상(흰색)에 비해 
너무 밝게 튀어 제가 채도를 대략 10%정도 낮춰
두 색상이 조화롭게 맞추긴 했지만,
이제 정말 멋진 메모 기능이 갖춰졌어요.

감사합니다.

**Comment by YeeF** [comment]
근데, 지금 확인해보니
난리가 났습니다 ㅎㅎㅎ

2단에 걸쳐 펼쳐보여지는 초록색 메모을 보고
기뻐 좋아서 댓글 바로 남겼는데,

예전 메모 했던 것들응 살펴보니

예전에는 1절에 메모했던 것이
1단에 주르륵 나왔다면

지금은 2단으로 나오지만,
2절 이나 3절 때로는 6, 8절 등 대중없이
1절에 나왔던 메모가 계속 반복적으로 나옵니다.

그 구절과 상관 없는 메모가 난리입니다. ㅋㅋ

**Comment by YeeF** [comment]
1단 보기에서는 
메모가 별표와 함께
각 구절에 맞게 정상적으로 표현이 됩니다.

다만, 
역본 이름이 메모 색인 초록색으로 나옵니다.

2단 보기에서는
역본이름 색과 메모색이 분리되었고
2단에 걸쳐 나오니 좋습니다만,

먼가 꼬였나봅니다.

다른 구절에  메모가 아무렇게 출현하고
마태복음 메모가 
창세기를 찾아가는데 거기에 등장하고 그렇습니다. 

역본 대조별 보기를 2단으로 볼 때
역본  별 본문과 메모가 별도로 진행되는건
정말 좋습니다. 
오히려, 1단 가로보기에서 분리안되고 같이 나오는 걸  수정해야겠지요.

그런데, 2단보기에서 메모가 뒤죽 박죽 섞이고
1단 가로보기에서는 정상 동작하는 건 2단을 수정해야하지 않나 싶습니다.

**Comment by lifoveBible** [comment]
네 테스트 해주셔서 감사합니다.
1단 보기에서 역본이름이 초록색인 것 확인했습니다.
2단 보기에서 메모가 다른 책과 장에서 똑같이 섞여 나오는 문제도 확인했습니다.

두 문제 모두 7.4.3 Beta2 버전에서 수정했습니다. 테스트 해보시고, 잘 되는지 또 알려주세요.
테스트 잘 해주시고 결과 알려주셔서 작업하기 수월했습니다.

**Comment by YeeF** [comment]
오..  말씀드린지 불과 몇 시간도 안돼서
이렇게 빠르게 착착 개선이 되다니 
그 실력이 참 멋지고,

사용자 입장에서 정말 감사드려요.

2단 보기에서 동일 메모가 여러 구절에
나타나던 문제가 드디어 해결돼어 정말 편합니다.
환상적인 사용이 되겠네요. 기쁩니다.

저는 역본 대조 기능인 2단 보기가 
사용하기 넘 유용하기 때문에 이렇게 사용하지만,

어떤 분들은 역본 대조 없이, 
또는 가로보기 기능을 통해 역본을 대조해볼지 모르겠네요.

1단 가로 보기에서도 가능하시면
역본 버젼들 나오기 전에 
각 구절에 해당하는 메모가 나온 뒤에
역본 버젼 들이 나오면 좋겠습니다.

현재는 1단 가로보기 에서는
역본 이름 나온 다음에 

그 역본 이름 길이만큼 밀린 채
들여쓰기 된 상태처럼 메모가 주우욱 나옵니다.

이게 2단 보기처럼 
메모 나온 뒤에
역본 별 이름과 구절이 나오면 더 좋겠습니다.

애쓰셨고 감사합니다.

**Comment by lifoveBible** [comment]
1단 보기 메모는 급한 것은 아니니 추후 작업을 위해 새 이슈로 따로 빼겠습니다.
https://github.com/lifoveBible/lifovebible/issues/60

**Comment by lifoveBible** [comment]
Affected in 7.4.3
