### ISSUE TITLE
메모 괄호없이 색지정할 수 있게

### ISSUE THREAD

**Issue by lifoveBible** [lifoveBible/lifovebible#55]

**Comment by YeeF** [comment]
괄호나 별표 대신 검은 바탕이니 초록색 등 미리 정해진 색을 사용하면 좋겠어요

**Comment by lifoveBible** [comment]
Affected in 7.4.2 Beta 2

**Comment by YeeF** [comment]
오늘 베타 버젼으로 보니 
메모 폰트 사이즈가 작아지도 초록색으로 
눈에 띄어 밑줄긋기나 일반 구절과 금방 구별되어 
정말 좋았습니다.

감사합니다.

다만, 역본 이름 마져도
색이 변해 초록색으로 나오더군요.

메모폰트 사이즈도 역본 이름 사이즈랑 
같게 처리된거 같구요.

메모는 구절 기능 이므로
메모 따로 역본명 따로 처리 되어야 하지 않을까
싶습니다.

그러나, 오늘 메일 받고 확인해보고
기뻐 글 남깁니다.

감사합니다.

**Comment by lifoveBible** [comment]
https://github.com/lifoveBible/lifovebible/issues/54
이거 수정되면서 자동으로 고쳐졌습니다.

확인해 보시고 문제있으면 또 알려주세요.

2017-07-17 3:39 GMT-04:00 YeeF <notifications@github.com>:

**Comment by YeeF** [comment]
네 환상적으로 바뀌었어요.

이제 2단 역본 대조를 본격적으로 사용할 수 있게 됐어요.


정말 감사드려요.

**Comment by YeeF** [comment]
역본 대조 기능으로 성경을 보다가
성경이 여러 개 택해지지 않고 
개역 하나만 택해졌을 경우

메모 기능이 
별표 등장하면서
절 표시 색상도 메모 색으로 바뀌어 나타납니다.

어차피 주로 2단 역본 대조를 보기에 
지쟁은 없으나

메모와 절을 분리시킨 작업을 하셧기에
남은 부스러기도 찾아서 말씀드립니다 ^^

**Comment by lifoveBible** [comment]
네 부스러기 확인했습니다. 수정되면 7.4.3 Beta3 버전으로 배포할 예정이니 나중에 받으시면 잘 되는지 테스트 부탁드립니다.
