### ISSUE TITLE
본문 글자 색 바꾼 후 2단 본문 만 바뀜

### ISSUE THREAD

**Issue by YeeF** [lifoveBible/lifovebible#61]
본문 글자 색의 명도를 약간 올림 후
2단 역본 대조 기능으로
개역한글과 새번역을 보는데
개역은 초기화 색상이고,
새번역는 수정한 색상으로 나타납니다.

**Comment by lifoveBible** [comment]
혹시 설정의 역본 순서 및 글자색 변경에서 개역색을 따로 지정해 주신 건 아닌지요?
그렇게 해서 바뀐 색은 계속 따로 변경해 주어야 합니다.

**Comment by YeeF** [comment]
역본 순서 및 글자색 변경에서
개역색을 따로 지정해 주진 않았는데,
그런 현상이 나타났습니다.
(그런 기능도 있다는 걸 처음 알았네요 ^^)

오늘 업데이트 후,
혹시 그럴 가능성이 있을까봐
본문 글씨색 및
역본 순서 및 글 색상 모두 초기화 해봤습니다.

지금은 정상적으로 나와요.

**Comment by unsoft** [comment]
리뷰에서도 남겼습니다만.. 
위젯에서 표시된 구절을 터치하면 해당 장 절로 이동하게 이동하면 좋을것 같습니다
부탁드립니다.
