### ISSUE TITLE
 절 간격 조절할 수 있는 옵션 추가

### ISSUE THREAD

**Issue by lifoveBible** [lifoveBible/lifovebible#62]
스토어 코멘트

**Comment by YeeF** [comment]
오.. 기대됩니다

**Comment by YeeF** [comment]
볼륨 키 이동시 절 간 이동하게 하려는 거군요.
점점 환상적으로 바뀌어 갑니다.

감사합니다.

개역 난외주 역본이 있는
베들레헴 프로그램 썼다가
메모(노트)기능이 전혀 연동이 안돼서
메모 기능이 아무 의미 없어서
라이포브 프로그램을 찾았는데
아주 최고입니다.

베들레헴 성경 모바일에 있던
개역 난외주 역본이 제공될 수 있나 궁금합니다.

난외주 역본 대신 
개역과 새번역을 2단 대조로
난외주 개역을 대신하는 셈이긴 합니다.

**Comment by lifoveBible** [comment]
저작권이 만료 됐으면 가능할 것 같은데...저작권 문제가 없으면 데이터를 보내주시겠습니까?

**Comment by lifoveBible** [comment]
@YeeF 절 사이 여백을 넣는 것은 볼륨 키 이동시 절 간 이동하고는 별로 상관이 없는 것 같은데, 무엇일 이야기 하신 것인지요? (볼륨키로 스크롤 설정에서 한 절 이동은 옵션이 이미 있습니다.)

**Comment by lifoveBible** [comment]
Affected in 7.4.4

**Comment by lifoveBible** [comment]
배경색 적용이 안됐음. 수정 필요.
