### ISSUE TITLE
본문화면에서 뒤로가기 두번 눌러서 앱 나오기 (홈버튼이랑 같은 액션)

### ISSUE THREAD

**Issue by lifoveBible** [lifoveBible/lifovebible#71]

**Comment by YeeF** [comment]
이거 옵션이죠?

조는 빼르게 뒤로 누르기 때문에
홈으로 가머리면..

**Comment by lifoveBible** [comment]
네 그러면 굳이 안말들어도 되는 기능이겠어요. 홈버튼 누르면 되니까요. 앱을 종료 후 마지막에 보던 곳으로 가고 싶어하시는 분들이 있어서 홈 버튼으로 나갔다 들어오면 된다고 알려 드렸는데, 뒤로가기 해서 앱을 끝나는게 심리적으로 편안하신 분들이 계신 것 같습니다.
